version: '3.8'

services:
  neo4j:
    image: neo4j:5
    container_name: neo4j-db
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/testPass123

      # APOC 플러그인 활성화
      NEO4J_PLUGINS: '["apoc"]'

      # APOC에서 모든 프로시저 허용
      NEO4J_dbms_security_procedures_unrestricted: 'apoc.*'
      NEO4J_dbms_security_procedures_allowlist: 'apoc.*'
    volumes:
      - neo4j-data:/data
    networks:
      - backend-network

volumes:
  neo4j-data:

networks:
  backend-network:
    driver: bridge
