CREATE DATABASE IF NOT EXISTS goingDB;
CREATE DATABASE IF NOT EXISTS goingtestDB;

CREATE USER IF NOT EXISTS 'test'@'%' IDENTIFIED BY 'testPW';

GRANT ALL PRIVILEGES ON goingDB.* TO 'test'@'%';
GRANT ALL PRIVILEGES ON goingtestDB.* TO 'test'@'%';

FLUSH PRIVILEGES;