name: CI with Gradle

on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  CI:
    name: Continuous Integration
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive
          fetch-depth: 0

      - name: Update git submodules
        run: git submodule update --init --recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Verify Backend_Config files
        run: |
          echo "Checking Backend_Config contents:"
          ls -al Backend_Config
          echo "Checking application files:"
          ls -al Backend_Config/application*.properties
          echo "File contents:"
          cat Backend_Config/application.properties
          cat Backend_Config/application-test.properties

      - name: Build and Test with Gradle Wrapper
        env:
          SPRING_PROFILES_ACTIVE: test
        run: |
          echo "▶ Running Gradle build and test..."
          ./gradlew --no-daemon clean build test \
          -Dspring.profiles.active=test \
          -Dspring.config.additional-location=file:./Backend_Config/application.properties,file:./Backend_Config/application-test.properties

      - name: Show test results summary
        if: success()
        run: |
          echo "All Spring Boot tests passed successfully!"

      - name: Mark failure if tests failed
        if: failure()
        run: |
          echo "Tests failed. Please check the test logs for detail"
          exit 1