name: CI with Gradle

on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  CI:
    name: Continuous Integration
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive
          fetch-depth: 0

      - name: Update git submodules
        run: git submodule update --init --recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Verify Backend_Config files
        run: |
          echo "Checking Backend_Config contents:"
          ls -al Backend_Config
          echo "Checking application files:"
          ls -al Backend_Config/application*.properties

      - name: Build with Gradle Wrapper
        env:
          SPRING_PROFILES_ACTIVE: test
        run: |
          echo "▶ Running Gradle build..."
          ./gradlew --no-daemon clean build

      - name: Show build results
        if: success()
        run: |
          echo "Build completed successfully!"

      - name: Mark failure if build failed
        if: failure()
        run: |
          echo "Build failed. Please check the logs for detail"
          exit 1